# Profil dev
# Clé API OpenAgenda (commune à tous les agendas)
openagenda.api-key=oa_pk_apDyEbJzesQRVtweBegCZnvSzekuTzgklToDXIAdfrDrwHQgMLVDpIiSDtLdZKAh

# Configuration par défaut (rétrocompatibilité LL-5006)
openagenda.agenda-uid=86244142
openagenda.source-name=OpenAgenda Ministere culture
