# Profil local

spring.datasource.url=jdbc:postgresql://localhost:5432/locallife
spring.datasource.username=locallife
spring.datasource.password=locallife
spring.datasource.driver-class-name=org.postgresql.Driver
